# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Cypress test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
      
      - name: Install dependencies
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      
      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          
      - name: Allure Report
        uses: simple-elf/allure-report-action@v1.6
        with:
           allure_results: allure-results
           allure_report: allure_report
      
      - name: Logs
        run: ls -R
        
      - name: Commit and push changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git checkout ${{ github.event.pull_request.head.ref }}
          git add .
          git commit -m "Automated commit by GitHub Actions"
          git push origin ${{ github.event.pull_request.head.ref }}

      - name: Merge PR if successful
        if: success()
        uses: pullreminders/merge-action@v1.3.0
        with:
          github_token: ${{ secrets.PERMISSION }}
          strategy: merge-commit
