name: Cypress test

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          record: true
          parallel: true
          start: npm run test:e2e
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          
      - name: Copy history folder
        run: cp -Rf ./docs/history ./allure-results/
          
      - name: Allure Report
        uses: simple-elf/allure-report-action@v1.6
        with:
           allure_results: allure-results
           allure_report: docs
           
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.2
        with:
          add: docs
